// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SGO.Infrastructure.Persistence.Context;

#nullable disable

namespace SGO.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SGOContext))]
    partial class SGOContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SGO.Domain.Fichas.FichaClinica", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<string>("Diagnostico")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime>("FechaCreacionUtc")
                        .HasColumnType("datetime");

                    b.Property<string>("MotivoConsulta")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("PacienteDocumento")
                        .HasColumnType("int");

                    b.Property<string>("Prescripciones")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("ProfesionalMatricula")
                        .HasColumnType("int");

                    b.Property<string>("TratamientosRealizados")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<Guid>("TurnoId")
                        .HasColumnType("char(36)");

                    b.Property<uint>("Version")
                        .HasColumnType("int unsigned");

                    b.HasKey("Id");

                    b.HasIndex("PacienteDocumento");

                    b.ToTable("fichas_clinicas", (string)null);
                });

            modelBuilder.Entity("SGO.Domain.Odontogramas.Odontograma", b =>
                {
                    b.Property<Guid>("FichaClinicaId")
                        .HasColumnType("char(36)");

                    b.Property<uint>("Version")
                        .HasColumnType("int unsigned");

                    b.HasKey("FichaClinicaId");

                    b.ToTable("odontogramas", (string)null);
                });

            modelBuilder.Entity("SGO.Domain.Pacientes.Paciente", b =>
                {
                    b.Property<int>("Documento")
                        .HasColumnType("int");

                    b.Property<bool>("Alergico")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("DetalleAlergias")
                        .HasColumnType("longtext");

                    b.Property<string>("DetalleEnfermedad")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<bool>("EnfermedadSistemica")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateOnly?>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NumeroAfiliado")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ObraSocial")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<uint>("Version")
                        .HasColumnType("int unsigned");

                    b.HasKey("Documento");

                    b.ToTable("pacientes", (string)null);
                });

            modelBuilder.Entity("SGO.Domain.Fichas.FichaClinica", b =>
                {
                    b.HasOne("SGO.Domain.Pacientes.Paciente", "Paciente")
                        .WithMany("FichasClinicas")
                        .HasForeignKey("PacienteDocumento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("SGO.Domain.Odontogramas.Odontograma", b =>
                {
                    b.HasOne("SGO.Domain.Fichas.FichaClinica", null)
                        .WithOne("Odontograma")
                        .HasForeignKey("SGO.Domain.Odontogramas.Odontograma", "FichaClinicaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("SGO.Domain.Odontogramas.PiezaDental", "Piezas", b1 =>
                        {
                            b1.Property<Guid>("OdontogramaId")
                                .HasColumnType("char(36)");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<string>("D")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar(50)");

                            b1.Property<string>("Estado")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar(50)");

                            b1.Property<int>("Fdi")
                                .HasColumnType("int");

                            b1.Property<string>("L")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar(50)");

                            b1.Property<string>("M")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar(50)");

                            b1.Property<string>("O")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar(50)");

                            b1.Property<string>("V")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar(50)");

                            b1.HasKey("OdontogramaId", "Id");

                            b1.ToTable("odontograma_piezas", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("OdontogramaId");
                        });

                    b.Navigation("Piezas");
                });

            modelBuilder.Entity("SGO.Domain.Fichas.FichaClinica", b =>
                {
                    b.Navigation("Odontograma")
                        .IsRequired();
                });

            modelBuilder.Entity("SGO.Domain.Pacientes.Paciente", b =>
                {
                    b.Navigation("FichasClinicas");
                });
#pragma warning restore 612, 618
        }
    }
}
